/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.CtrlAlumno;
import controlador.CtrlPadre;
import controlador.CtrlProfesor;
import controlador.CtrlSeguimiento;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
//import javax.swing.ImageIcon;
import modelo.alumno.ConsultasAlumno;
import modelo.alumno.ModAlumno;
import modelo.alumno.ValidacionesAlumnos;
import modelo.padre.ConsultasPadre;
import modelo.padre.ModPadre;
import modelo.padre.ValidacionesPadre;
import modelo.profesor.ConsultasProfesor;
import modelo.profesor.ModProfesor;
import modelo.seguimiento.ConsultasSeguimiento;
import modelo.seguimiento.ModSeguimiento;
import modelo.seguimiento.ValidacionesSeguimientos;
import modelo.profesor.ValidacionesProfesor;




public class frmPrincipal extends javax.swing.JFrame {

  
    public frmPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoSSC.png")).getImage());
       // Crea un icono que referencie a la imagen en disco
        ImageIcon iconoOriginal;
        int ancho = 70; // ancho en pixeles que tendra el icono escalado
        int alto = -1; // alto (para que conserve la proporcion pasam -1)
        
        iconoOriginal = new ImageIcon(getClass().getResource("/imagenes/periodico.png"));
         // Obtiene un icono en escala con las dimensiones especificadas
        ImageIcon iconoEscala = new ImageIcon(iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        //<editor-fold defaultstate="collapsed" desc="comment">
        this.btnRegistro.setIcon(iconoEscala);
         //</editor-fold>
        
        iconoOriginal = new ImageIcon(getClass().getResource("/imagenes/estudiante.png"));
        // Obtiene un icono en escala con las dimensiones especificadas
        iconoEscala = new ImageIcon(iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        //ImageIcon iconoEscala = new ImageIcon(iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        //<editor-fold defaultstate="collapsed" desc="comment">
        this.btnAlumno.setIcon(iconoEscala);
        //</editor-fold>
        
         iconoOriginal = new ImageIcon(getClass().getResource("/imagenes/familia.png"));
        // Obtiene un icono en escala con las dimensiones especificadas
        iconoEscala = new ImageIcon(iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        //ImageIcon iconoEscala = new ImageIcon(iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        //<editor-fold defaultstate="collapsed" desc="comment">
        this.btnPadre.setIcon(iconoEscala);
        //</editor-fold>
        
        ancho=90;
        iconoOriginal = new ImageIcon(getClass().getResource("/imagenes/maestro.png"));
        // Obtiene un icono en escala con las dimensiones especificadas
        iconoEscala = new ImageIcon(iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        //ImageIcon iconoEscala = new ImageIcon(iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        //<editor-fold defaultstate="collapsed" desc="comment">
        this.btnProfesor.setIcon(iconoEscala);
        //</editor-fold>
        
        alto=90;
        ancho=-1;                
        iconoOriginal = new ImageIcon(getClass().getResource("/imagenes/salida.png"));
        // Obtiene un icono en escala con las dimensiones especificadas
        iconoEscala = new ImageIcon(iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        //ImageIcon iconoEscala = new ImageIcon(iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_DEFAULT));
        this.btnSalir.setIcon(iconoEscala);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlumno = new javax.swing.JButton();
        btnPadre = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnProfesor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblInforme = new javax.swing.JLabel();
        lblRegistros = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Seguimiento de Coordinación");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        btnAlumno.setBackground(java.awt.SystemColor.controlHighlight);
        btnAlumno.setToolTipText("Registro de Alumnos");
        btnAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlumnoMouseEntered(evt);
            }
        });
        btnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnoActionPerformed(evt);
            }
        });

        btnPadre.setBackground(java.awt.SystemColor.controlHighlight);
        btnPadre.setToolTipText("Registro de Padres");
        btnPadre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPadreMouseEntered(evt);
            }
        });
        btnPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadreActionPerformed(evt);
            }
        });

        btnRegistro.setBackground(java.awt.SystemColor.controlHighlight);
        btnRegistro.setToolTipText("Informes de Seguimiento");
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroMouseEntered(evt);
            }
        });
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnProfesor.setBackground(java.awt.SystemColor.controlHighlight);
        btnProfesor.setToolTipText("Registro de Profesores");
        btnProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfesorMouseEntered(evt);
            }
        });
        btnProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesorActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 150)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("S");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 219));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("istema de");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 202, 219));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 150)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("S");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, 219));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("eguimiento de");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 304, 219));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("oorinación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 240, 219));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 150)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("C");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, 219));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Versión 1.0 MySQL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, 190, -1));

        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblInforme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRegistros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1309, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(btnAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnoActionPerformed
        // TODO add your handling code here:
        
        frmAlumno alumno=new frmAlumno();
        ModAlumno modAl=new ModAlumno();
        ConsultasAlumno consAl=new ConsultasAlumno();
        ValidacionesAlumnos validAl=new ValidacionesAlumnos();
        
        CtrlAlumno control=new CtrlAlumno(alumno,modAl,consAl,validAl );
        
        alumno.setLocationRelativeTo(null);
        alumno.setSize(600,525);
        alumno.setVisible(true);
        alumno.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoSSC.png")).getImage());
        //Carga el cop de Padres con todos los nombres existentes
        consAl.cargaComboPadres(modAl, alumno);
        //Carga el ComboAlumnos con todos los nombres existentes para Buscador
        consAl.cargaComboAlumnos(modAl, alumno);
       
                
        
    }//GEN-LAST:event_btnAlumnoActionPerformed

    private void btnPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadreActionPerformed
        
        frmPadre frmPadre=new frmPadre();
        ModPadre modPadre=new ModPadre();
        ConsultasPadre consPadre=new ConsultasPadre();
        ValidacionesPadre valPadre=new ValidacionesPadre();
        CtrlPadre ctrlPadre=new CtrlPadre(frmPadre,modPadre,consPadre,valPadre);
        
        
        frmPadre.setLocationRelativeTo(null);
        frmPadre.setVisible(true);
        consPadre.cargaComboPadre(modPadre, frmPadre);
        frmPadre.jlblId.setVisible(false);
        frmPadre.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoSSC.png")).getImage());
    }//GEN-LAST:event_btnPadreActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        ModSeguimiento modSeg=new ModSeguimiento();
        frmSeguimiento frmSeg=new frmSeguimiento();
        frmRegSeguimiento frmRegSeg=new frmRegSeguimiento();
        ConsultasSeguimiento consSeg=new ConsultasSeguimiento();
        ValidacionesSeguimientos validSeg=new ValidacionesSeguimientos();
        frmSeg.setTitle("DETALLE DEL REGISTRO DE SEGUIMIENTO");
        
        CtrlSeguimiento control=new CtrlSeguimiento(frmRegSeg,modSeg,consSeg,frmSeg,validSeg );
        
        frmSeg.setLocationRelativeTo(null);
        frmSeg.setVisible(true);
        frmSeg.setExtendedState(frmPrincipal.MAXIMIZED_BOTH);
//**************        
        frmSeg.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoSSC.png")).getImage());
        
        
        //CargaDatosTabla carga=new CargaDatosTabla();
        int tipoBusqueda=0;
        frmSeg.jtSeguimiento.setModel(consSeg.verDetalleSeguimiento(frmSeg,tipoBusqueda));
        //frmSeg.jtSeguimiento.setModel(consSeg.verDetalleSeguimiento(modSeg, frmSeg));
        modSeg.setTipoReporte(0);//defino reporte estandar con los datos de la carga inicial de la Grilla
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesorActionPerformed
        frmProfesor frmProf=new frmProfesor();
        ModProfesor modProf=new ModProfesor();
        ConsultasProfesor consProf=new ConsultasProfesor();
        ValidacionesProfesor valProf=new ValidacionesProfesor();
        CtrlProfesor ctrlProf=new CtrlProfesor(frmProf,modProf,consProf,valProf);
        
        
        frmProf.setLocationRelativeTo(null);
        frmProf.setVisible(true);
        consProf.cargaComboProfesor(modProf, frmProf);
        frmProf.jlblId.setVisible(false);
        frmProf.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoSSC.png")).getImage());
    }//GEN-LAST:event_btnProfesorActionPerformed

    private void btnRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseEntered
        // TODO add your handling code here:
        lblInforme.setText("Informe de Seguimiento");
    }//GEN-LAST:event_btnRegistroMouseEntered

    private void btnAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnoMouseEntered
        lblRegistros.setText("Registro de Alumnos");
    }//GEN-LAST:event_btnAlumnoMouseEntered

    private void btnPadreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPadreMouseEntered
        lblRegistros.setText("Registro de Padres");
    }//GEN-LAST:event_btnPadreMouseEntered

    private void btnProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesorMouseEntered
        lblRegistros.setText("Registro de Profesores");
    }//GEN-LAST:event_btnProfesorMouseEntered

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        lblRegistros.setText("");
        lblInforme.setText("");
        lblSalir.setText("");
    }//GEN-LAST:event_formMouseEntered

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        lblSalir.setText("Salir de la Aplicación");
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumno;
    private javax.swing.JButton btnPadre;
    private javax.swing.JButton btnProfesor;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInforme;
    private javax.swing.JLabel lblRegistros;
    private javax.swing.JLabel lblSalir;
    // End of variables declaration//GEN-END:variables
}
