/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Samsung
 */
public class frmRegSeguimiento extends javax.swing.JFrame {

    /**
     * Creates new form frmSeguimiento
     */
    public frmRegSeguimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanelSeg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtxtIdProf = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jcbxProfesor = new javax.swing.JComboBox();
        btnEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfDetalle = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        jtxtDni = new javax.swing.JTextField();
        jtxtCurso = new javax.swing.JTextField();
        jftxtFecha = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbxMotivo = new javax.swing.JComboBox();
        jcbxAlumno = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jtxtIdSeg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Seguimiento de Coordinacion");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("REGISTRO DE SITUACIÓN");

        jPanelSeg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DETALLE");
        jPanelSeg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jtxtIdProf.setText("id_prof");
        jPanelSeg.add(jtxtIdProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ALUMNO");
        jPanelSeg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        btnAlta.setBackground(java.awt.SystemColor.controlHighlight);
        btnAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAlta.setText("Alta");
        btnAlta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        jPanelSeg.add(btnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("INFORME");
        jPanelSeg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel8.setText("PROFESOR");
        jPanelSeg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        btnModificar.setBackground(java.awt.SystemColor.controlHighlight);
        btnModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.setEnabled(false);
        jPanelSeg.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 100, 40));

        jcbxProfesor.setEnabled(false);
        jPanelSeg.add(jcbxProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 210, -1));

        btnEliminar.setBackground(java.awt.SystemColor.controlHighlight);
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setEnabled(false);
        jPanelSeg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 100, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("DNI Nº");
        jPanelSeg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        btnCancelar.setBackground(java.awt.SystemColor.controlHighlight);
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setEnabled(false);
        jPanelSeg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 100, 40));

        jtfDetalle.setColumns(20);
        jtfDetalle.setRows(5);
        jtfDetalle.setEnabled(false);
        jScrollPane1.setViewportView(jtfDetalle);

        jPanelSeg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 620, 150));

        btnGuardar.setBackground(java.awt.SystemColor.controlHighlight);
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setEnabled(false);
        jPanelSeg.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 100, 40));

        jtxtDni.setEditable(false);
        jPanelSeg.add(jtxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 100, -1));

        jtxtCurso.setEditable(false);
        jPanelSeg.add(jtxtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 100, -1));

        try {
            jftxtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####   ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtFecha.setText("01/01/2000      ");
        jftxtFecha.setEnabled(false);
        jPanelSeg.add(jftxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 100, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("CURSO");
        jPanelSeg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jcbxMotivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Coordinacion", "Direccion", "Familia", "Gabinete", "Profesor" }));
        jcbxMotivo.setEnabled(false);
        jPanelSeg.add(jcbxMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 170, -1));

        jcbxAlumno.setEnabled(false);
        jPanelSeg.add(jcbxAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 360, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("FECHA");
        jPanelSeg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jtxtIdSeg.setText("id_seg");
        jPanelSeg.add(jtxtIdSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanelSeg, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegSeguimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAlta;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanelSeg;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox jcbxAlumno;
    public javax.swing.JComboBox jcbxMotivo;
    public javax.swing.JComboBox jcbxProfesor;
    public javax.swing.JFormattedTextField jftxtFecha;
    public javax.swing.JTextArea jtfDetalle;
    public javax.swing.JTextField jtxtCurso;
    public javax.swing.JTextField jtxtDni;
    public javax.swing.JLabel jtxtIdProf;
    public javax.swing.JLabel jtxtIdSeg;
    // End of variables declaration//GEN-END:variables
}
