/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.seguimiento.ConsultasSeguimiento;

/**
 *
 * @author Samsung
 */
public class frmSeguimiento extends javax.swing.JFrame  {

    /** Creates new form frmSeguiminento */
    public frmSeguimiento() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSeguimiento = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtDetalle = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jtxtProfesor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtMateria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPadre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jchbFecha = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jrbNombre = new javax.swing.JRadioButton();
        jrbDni = new javax.swing.JRadioButton();
        jcbNombre = new javax.swing.JComboBox<>();
        jcbDni = new javax.swing.JComboBox<>();
        jchbNombre = new javax.swing.JCheckBox();
        jbBuscar = new javax.swing.JButton();
        jftxtFechaDesde = new javax.swing.JFormattedTextField();
        jftxtFechaHasta = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jbtnImprimir = new javax.swing.JButton();
        btnModificarInforme = new javax.swing.JButton();
        btnEliminarInforme = new javax.swing.JButton();
        btnGenerarInforme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtSeguimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtSeguimiento);

        jtxtDetalle.setColumns(20);
        jtxtDetalle.setRows(5);
        jScrollPane2.setViewportView(jtxtDetalle);

        jLabel1.setText("DETALLE");

        jLabel2.setText("PROFESOR");

        jLabel3.setText("MATERIA");

        jLabel4.setText("PADRES");

        jLabel5.setText("TELEFONO");

        jLabel6.setText("E-MAIL");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel7.setText("Búsqueda");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 13, 94, -1));

        jchbFecha.setText("Fecha");
        jchbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbFechaActionPerformed(evt);
            }
        });
        jPanel1.add(jchbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel8.setText("Desde");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel9.setText("Hasta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 51, -1));

        buttonGroup1.add(jrbNombre);
        jrbNombre.setSelected(true);
        jrbNombre.setText("Nombre");
        jrbNombre.setEnabled(false);
        jrbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jrbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        buttonGroup1.add(jrbDni);
        jrbDni.setText("DNI");
        jrbDni.setEnabled(false);
        jPanel1.add(jrbDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jcbNombre.setEnabled(false);
        jPanel1.add(jcbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 280, -1));

        jcbDni.setEnabled(false);
        jPanel1.add(jcbDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 161, -1));

        jchbNombre.setText("Alumno");
        jchbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jchbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jbBuscar.setText("Buscar");
        jPanel1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 366, 40));

        jftxtFechaDesde.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            jftxtFechaDesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtFechaDesde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtFechaDesde.setText("01/01/2000    ");
        jftxtFechaDesde.setEnabled(false);
        jPanel1.add(jftxtFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 109, -1));

        jftxtFechaHasta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            jftxtFechaHasta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftxtFechaHasta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftxtFechaHasta.setText("01/01/2000    ");
        jftxtFechaHasta.setEnabled(false);
        jPanel1.add(jftxtFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 109, -1));

        jLabel10.setText("( dd/mm/yyyy )");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 97, -1));

        jbtnImprimir.setText("Imprimir");
        jbtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 260, 100, 70));

        btnModificarInforme.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnModificarInforme.setText("Modificar Informe");
        btnModificarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarInformeActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, 30));

        btnEliminarInforme.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnEliminarInforme.setText("Eliminar Informe");
        jPanel1.add(btnEliminarInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 120, 30));

        btnGenerarInforme.setText("Generar Informe");
        btnGenerarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarInformeActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtMateria))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtEmail)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jtxtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchbFechaActionPerformed

    private void jrbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbNombreActionPerformed

    private void jchbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchbNombreActionPerformed

    private void jbtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnImprimirActionPerformed

    private void btnModificarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarInformeActionPerformed
      
    }//GEN-LAST:event_btnModificarInformeActionPerformed

    private void btnGenerarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarInformeActionPerformed
        // TODO add your handling code here:
        //frmRegSeguimiento frmRegSeg=new frmRegSeguimiento();
        //frmRegSeg.setVisible(true);
    }//GEN-LAST:event_btnGenerarInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSeguimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminarInforme;
    public javax.swing.JButton btnGenerarInforme;
    public javax.swing.JButton btnModificarInforme;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbBuscar;
    public javax.swing.JButton jbtnImprimir;
    public javax.swing.JComboBox<String> jcbDni;
    public javax.swing.JComboBox<String> jcbNombre;
    public javax.swing.JCheckBox jchbFecha;
    public javax.swing.JCheckBox jchbNombre;
    public javax.swing.JFormattedTextField jftxtFechaDesde;
    public javax.swing.JFormattedTextField jftxtFechaHasta;
    public javax.swing.JRadioButton jrbDni;
    public javax.swing.JRadioButton jrbNombre;
    public javax.swing.JTable jtSeguimiento;
    public javax.swing.JTextArea jtxtDetalle;
    public javax.swing.JTextField jtxtEmail;
    public javax.swing.JTextField jtxtMateria;
    public javax.swing.JTextField jtxtPadre;
    public javax.swing.JTextField jtxtProfesor;
    public javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables

}
